package com.example.secdsp.modules.sellerperformance.dto.response;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.experimental.FieldDefaults;

import java.math.BigDecimal;

@Schema(
    description = "Top-selling product information."
)
@Builder
@Getter
@FieldDefaults(level = AccessLevel.PRIVATE)
public class TopProductResponse {

    @Schema(
        description = "Product ID.",
        example = "101"
    )
    Long productId;

    @Schema(
        description = "Product name.",
        example = "Wireless Mouse"
    )
    String productName;

    @Schema(
        description = "Total quantity sold.",
        example = "325"
    )
    Long quantitySold;

    @Schema(
        description = "Revenue generated by the product.",
        example = "8450000"
    )
    BigDecimal revenue;
}
