CREATE TABLE carts
(
    id         BIGSERIAL PRIMARY KEY,

    user_id    BIGINT    NOT NULL UNIQUE
        REFERENCES users (id),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);