-- V41: Seed rich Vietnamese product reviews for demo catalog.
-- Idempotent: unique (user_id, product_id) where deleted_at IS NULL.

-- Chuẩn hoá comment tiếng Anh từ V29 → tiếng Việt (nếu còn)
UPDATE product_reviews pr
SET comment = v.comment,
    updated_at = CURRENT_TIMESTAMP
FROM (
    VALUES
        ('customer01@gmail.com', 'iphone-15-pro-128gb',
         'Máy mượt, camera đêm rõ. Giao hàng đúng hẹn, đóng gói chắc chắn.'),
        ('customer01@gmail.com', 'men-slim-fit-blazer',
         'Vải đẹp, form gọn. Nên thử size trước vì hơi rộng vai.'),
        ('customer02@gmail.com', 'modern-sofa-3-seater',
         'Nệm êm, vải dễ lau. Ship lắp đặt đúng hẹn.'),
        ('customer02@gmail.com', 'air-fryer-5l',
         'Chiên ít dầu, dễ vệ sinh. Công thức trong hộp hữu ích.'),
        ('customer03@gmail.com', 'adjustable-dumbbell-20kg',
         'Chỉnh tạ nhanh, tay cầm chắc. Tập tại nhà rất tiện.'),
        ('customer03@gmail.com', 'google-pixel-9',
         'Ảnh tự nhiên, cập nhật Android sạch. Pin đủ ngày.'),
        ('customer03@gmail.com', 'oversized-hoodie',
         'Form rộng đẹp, vải dày vừa. Giặt không xù nhiều.')
) AS v(email, slug, comment)
JOIN users u ON u.email = v.email
JOIN products p ON p.slug = v.slug AND p.deleted_at IS NULL
WHERE pr.user_id = u.id
  AND pr.product_id = p.id
  AND pr.deleted_at IS NULL
  AND pr.comment IS DISTINCT FROM v.comment;

INSERT INTO product_reviews (product_id, user_id, rating, comment, created_at, updated_at)
SELECT p.id, u.id, v.rating, v.comment,
       CURRENT_TIMESTAMP - (v.days_ago || ' days')::interval,
       CURRENT_TIMESTAMP - (v.days_ago || ' days')::interval
FROM (VALUES
    ('customer02@gmail.com', 'iphone-15-pro-128gb', 4,
     'Pin ổn trong ngày. Giá hơi cao nhưng đúng chuẩn hàng chính hãng.', 8),
    ('customer04@gmail.com', 'iphone-15-pro-128gb', 5,
     'Đổi từ Android sang — làm quen nhanh, Face ID cực tiện.', 12),
    ('customer05@gmail.com', 'samsung-galaxy-s24', 5,
     'Màn đẹp, AI dịch nhanh. Shop tư vấn nhiệt tình.', 5),
    ('customer06@gmail.com', 'samsung-galaxy-s24', 4,
     'Sạc nhanh ổn. Camera zoom xa hơi mềm nhưng đủ dùng.', 15),
    ('customer01@gmail.com', 'macbook-air-m3', 5,
     'Nhẹ, êm, pin cả ngày. Code và họp Zoom không nóng máy.', 6),
    ('customer03@gmail.com', 'macbook-air-m3', 5,
     'Màn đẹp, bàn phím êm. Đáng tiền nếu hay mang đi làm.', 18),
    ('customer07@gmail.com', 'airpods-pro-2', 5,
     'Chống ồn tốt trên xe bus. Fit tai ổn sau vài ngày đeo.', 4),
    ('customer08@gmail.com', 'airpods-pro-2', 4,
     'Bass rõ. Case hơi trầy nếu bỏ túi chung chìa khóa.', 11),
    ('customer02@gmail.com', 'ipad-air-6', 5,
     'Vẽ note học bài rất đã. Pencil mượt, pin đủ buổi học.', 7),
    ('customer09@gmail.com', 'dell-xps-15', 4,
     'Màn đẹp, bàn phím chắc. Hơi nặng nếu mang laptop cả ngày.', 9),
    ('customer10@gmail.com', 'dell-xps-15', 5,
     'Cấu hình mạnh cho edit video nhẹ. Shop giao đúng model.', 14),
    ('customer04@gmail.com', 'hp-spectre-x360', 4,
     'Gập 360 tiện. Touch màn ổn, loa hơi nhỏ.', 16),
    ('customer05@gmail.com', 'xiaomi-14-ultra', 5,
     'Camera Leica đẹp, sạc siêu nhanh. Giá hợp lý hơn flagship khác.', 2),
    ('customer06@gmail.com', 'logitech-mx-master-3s', 5,
     'Chuột êm, con lăn ngang tiện spreadsheet. Pin lâu.', 10),
    ('customer07@gmail.com', 'samsung-t7-ssd-1tb', 5,
     'Copy file nhanh, nhỏ gọn. Đã backup cả thư mục dự án.', 13),
    ('customer08@gmail.com', 'men-casual-shirt', 5,
     'Cotton mềm, giặt không xù. Mặc đi làm thoải mái.', 6),
    ('customer09@gmail.com', 'women-floral-dress', 5,
     'Hoa nhẹ nhàng, cắt may sạch. Đúng size bảng hướng dẫn.', 8),
    ('customer10@gmail.com', 'women-office-skirt', 4,
     'Công sở ổn. Vải đứng form, dài vừa chân.', 17),
    ('customer01@gmail.com', 'leather-oxford-shoes', 5,
     'Da thật, đi êm sau khi break-in. Đóng gói cẩn thận.', 11),
    ('customer03@gmail.com', 'centella-facial-cleanser', 5,
     'Rửa mặt dịu, không khô. Dùng được da nhạy cảm.', 4),
    ('customer04@gmail.com', 'vitamin-c-serum-30ml', 4,
     'Da sáng dần sau ~2 tuần. Mùi nhẹ, thấm nhanh.', 9),
    ('customer05@gmail.com', 'matte-lipstick-set', 5,
     'Màu chuẩn ảnh, lâu trôi. Set đủ dùng tuần.', 7),
    ('customer06@gmail.com', 'hyaluronic-acid-serum', 5,
     'Cấp ẩm tốt, không dính. Kết hợp kem chống nắng ổn.', 12),
    ('customer07@gmail.com', 'cushion-foundation', 4,
     'Che phủ vừa, finish tự nhiên. Tone hơi sáng với da ngăm.', 15),
    ('customer09@gmail.com', 'wooden-dining-table', 4,
     'Gỗ chắc, mặt nhẵn. Hơi nặng khi kê lại.', 19),
    ('customer10@gmail.com', 'wall-art-canvas', 5,
     'In nét, khung chắc. Treo phòng khách rất ổn.', 5),
    ('customer01@gmail.com', 'non-stick-cookware-set', 5,
     'Chống dính tốt, rửa dễ. Đủ size nấu ngày thường.', 8),
    ('customer02@gmail.com', 'led-standing-lamp', 4,
     'Ánh sáng ấm, chỉnh độ cao tiện. Chân đế vững.', 13),
    ('customer04@gmail.com', 'yoga-mat-premium', 5,
     'Chống trượt tốt, dày vừa. Không hôi mùi cao su.', 6),
    ('customer05@gmail.com', 'treadmill-pro-x', 4,
     'Chạy êm, màn hình rõ. Lắp đặt cần khoảng trống đủ rộng.', 22),
    ('customer06@gmail.com', 'camping-tent-4-person', 5,
     'Dựng nhanh, chống mưa ổn. Gia đình 3 người thoải mái.', 10),
    ('customer07@gmail.com', 'hiking-backpack-40l', 5,
     'Đai lưng êm, ngăn nhiều. Đi trekking 2 ngày ổn.', 14),
    ('customer09@gmail.com', 'galaxy-tab-s9', 4,
     'Màn AMOLED đẹp, S Pen mượt. Hơi phản chiếu ngoài nắng.', 11),
    ('customer10@gmail.com', 'anker-65w-charger', 5,
     'Sạc laptop + điện thoại cùng lúc. Nhỏ gọn mang đi.', 2),
    ('customer01@gmail.com', 'oneplus-12', 5,
     'Mượt, sạc nhanh. Camera selfie ổn trong tầm giá.', 9),
    ('customer02@gmail.com', 'wireless-charging-pad', 4,
     'Sạc ổn định. Cần đặt đúng tâm mới đầy tốc độ.', 16),
    ('customer04@gmail.com', 'high-waist-jeans', 4,
     'Ôm eo đẹp. Nên chọn size theo bảng shop.', 12),
    ('customer05@gmail.com', 'sneakers-street-pro', 5,
     'Êm chân, đế bám. Đi cả ngày không đau gót.', 7),
    ('customer06@gmail.com', 'graphic-tshirt', 5,
     'In bền, cotton mềm. Giá dễ mua thêm màu khác.', 18),
    ('customer07@gmail.com', 'crop-top-basic', 4,
     'Basic dễ phối. Co giãn tốt, không lộ đường may.', 20),
    ('customer08@gmail.com', 'air-fryer-5l', 5,
     'Giỏ đủ 4–5 người. Khoai tây giòn, dễ vệ sinh.', 3),
    ('customer09@gmail.com', 'blender-1000w', 5,
     'Xay sinh tố mịn, ồn vừa phải. Cối dễ tháo rửa.', 8),
    ('customer10@gmail.com', 'electric-kettle-18l', 4,
     'Sôi nhanh, tự ngắt. Vòi rót hơi nhỏ với bình to.', 15),
    ('customer01@gmail.com', 'ceramic-vase-decor', 5,
     'Men đẹp, đứng vững. Decor bàn ăn rất xinh.', 11),
    ('customer02@gmail.com', 'wall-clock-modern', 4,
     'Kim êm, thiết kế tối giản. Pin AA dùng lâu.', 17),
    ('customer03@gmail.com', 'sleeping-bag-winter', 5,
     'Ấm thật, túi nén gọn. Đã dùng cắm trại Đà Lạt.', 6),
    ('customer04@gmail.com', 'portable-gas-stove', 5,
     'Nhỏ gọn, lửa đều. Nấu mì ngoài trời rất tiện.', 9),
    ('customer05@gmail.com', 'resistance-band-set', 5,
     'Đủ mức lực, túi đựng gọn. Tập phục hồi khớp tốt.', 4),
    ('customer06@gmail.com', 'camping-table-foldable', 4,
     'Gấp gọn, mặt chắc. Chân hơi cao với ghế thấp.', 13),
    ('customer07@gmail.com', 'outdoor-flashlight-pro', 5,
     'Sáng mạnh, chống nước ổn. Pin sạc nhanh.', 2),

    -- Sản phẩm seed V24 (seller@sedsp.vn)
    ('customer01@gmail.com', 'tai-nghe-bluetooth-pro-anc', 5,
     'ANC cắt ồn tốt trên xe. Pin nghe liên tục gần cả ngày.', 5),
    ('customer02@gmail.com', 'tai-nghe-bluetooth-pro-anc', 4,
     'Bass rõ, đệm tai êm. App EQ hơi đơn giản.', 12),
    ('customer03@gmail.com', 'tai-nghe-bluetooth-pro-anc', 5,
     'Đáng mua trong tầm giá. Ghép Bluetooth ổn định.', 19),
    ('customer@sedsp.vn', 'tai-nghe-bluetooth-pro-anc', 5,
     'Dùng họp online + nghe nhạc — mic rõ, đeo lâu không đau.', 7),
    ('customer04@gmail.com', 'ban-phim-co-rgb-keypro-k87', 5,
     'Switch đỏ êm, RGB đẹp. Khung chắc, không bị cong.', 6),
    ('customer05@gmail.com', 'ban-phim-co-rgb-keypro-k87', 4,
     'Gõ đã tay. Keycap hơi bóng sau vài tuần.', 14),
    ('customer@sedsp.vn', 'ban-phim-co-rgb-keypro-k87', 5,
     'Layout 87 phím vừa bàn làm việc. Hotswap tiện thay switch.', 10),
    ('customer06@gmail.com', 'giay-chay-bo-airflex-marathon', 5,
     'Đệm êm, chạy 10km không đau gối. Size chuẩn bảng EU.', 4),
    ('customer07@gmail.com', 'giay-chay-bo-airflex-marathon', 4,
     'Thoáng khí tốt. Đế hơi trơn khi trời mưa.', 16),
    ('customer@sedsp.vn', 'giay-chay-bo-airflex-marathon', 5,
     'Nhẹ, ôm chân. Đã mua thêm đôi thứ hai cho tập gym.', 21),
    ('customer08@gmail.com', 'noi-chien-khong-dau-5l', 5,
     'Giỏ 5L đủ gia đình. Chiên khoai giòn, dễ rửa.', 3),
    ('customer09@gmail.com', 'noi-chien-khong-dau-5l', 4,
     'Hẹn giờ tiện. Vỏ hơi nóng khi chạy lâu.', 11),
    ('customer@sedsp.vn', 'noi-chien-khong-dau-5l', 5,
     'Thay nồi dầu cũ — sạch hơn, mùi ít lan nhà.', 8)
) AS v(email, slug, rating, comment, days_ago)
JOIN users u ON u.email = v.email AND u.deleted_at IS NULL
JOIN products p ON p.slug = v.slug AND p.deleted_at IS NULL
WHERE NOT EXISTS (
    SELECT 1 FROM product_reviews pr
    WHERE pr.user_id = u.id
      AND pr.product_id = p.id
      AND pr.deleted_at IS NULL
);
